### ISSUE TITLE
Alternate to AWS move: Linode VPS

### ISSUE THREAD

**Issue by nickv2002** [sumpfork/bgtools_web#22]
Hey Peter thanks for the [detailed transition info](https://boardgamegeek.com/thread/926575/article/36331437#36331437). If this doesn’t work out for some reason I have a tiny virtual server running Ubuntu on Linode that should have spare capacity to run the Python tools you need. I’m not sure about setting up all the hooks etc that you usually use to deploy (as I don’t have much experience with all the AWS tech) but it should be straightforward enough to run some Python server code at a given URL.

In any case, my point is if this AWS transition doesn’t work our LMK and we can look into an alternate approach.

**Comment by sumpfork** [comment]
Thanks, but aws transition is all done.
